version: '3'
services:
  postgres:
    image: 'postgres:18-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-solid-saas}
      POSTGRES_USER: ${POSTGRES_USER:-solid}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-solid}
    restart: always
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.4'
    ports:
      - '8080:8080'
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-solid}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-solid}
      KC_HTTP_ENABLED: false
    command: start-dev --import-realm
    volumes:
      - ../auth-settings/import:/opt/keycloak/data/import
      - type: bind
        source: ../auth-settings/themes
        target: /opt/keycloak/themes
